defaults:
  - _self_
  - hydra: default
  - experiment: null

save_dir: "logs/"
seed: 27

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: "yoshua-bengio"
  project: "Complexity - ${experiment.name}"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: ${save_dir}
  offline: False
  tags: null